name: ecotrack
description: Aplicaci贸n m贸vil para calcular y gestionar la huella de carbono personal.

# No se publicar谩 en pub.dev
publish_to: 'none'

# Versi贸n de la app
version: 1.0.0+1

#  SDK compatible
environment:
  sdk: '>=3.9.0 <4.0.0'

#  Dependencias principales
dependencies:
  flutter:
    sdk: flutter

  # conos iOS
  cupertino_icons: ^1.0.2

  # Gesti贸n de estado (BLoC)
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7

  # Inyecci贸n de dependencias
  get_it: ^7.7.0

  # Conexi贸n con Supabase
  supabase_flutter: ^2.10.1

  # Programaci贸n funcional (manejo de errores)
  dartz: ^0.10.1

#  Dependencias de desarrollo
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

#  Configuraci贸n de Flutter
flutter:
  uses-material-design: true
